### ISSUE TITLE
How to turn emoji off?

### ISSUE THREAD

**Issue by ghostsquad** [vivaxy/gacp#118]
Is there a way to turn emoji off entirely?

**Comment by vivaxy** [comment]
@ghostsquad Sorry, there is no way to turn off emoji.

**Comment by itpropro** [comment]
You can just press enter when prompted for the Gitmoji, but I think it's a good practice to have it enabled by default and when you want to skip it, just press enter. For more distributed workflows, you can configure it in the config now afaik.

**Comment by ghostsquad** [comment]
The question was posed to improve the experience of those who do not wish emoji in their commits, thus would want to turn in completely off, and not be burdened by an extra prompt they would never use.

**Comment by ghostsquad** [comment]
> You can just press enter when prompted for the Gitmoji, but I think it's a good practice to have it enabled by default and when you want to skip it, just press enter. For more distributed workflows, you can configure it in the config now afaik.

You can disable it in `.gacprc` ? If so, does that mean the `"emoji"` field supports either a string or a boolean?

**Comment by vivaxy** [comment]
> > You can just press enter when prompted for the Gitmoji, but I think it's a good practice to have it enabled by default and when you want to skip it, just press enter. For more distributed workflows, you can configure it in the config now afaik.
> 
> You can disable it in `.gacprc` ? If so, does that mean the `"emoji"` field supports either a string or a boolean?

"emoji" field can be "emoji" for "😀", "code" for ": grinning:" or "none" for no emoji.
