### ISSUE TITLE
Consider slowing down the `gif` on the readme

### ISSUE THREAD

**Issue by ghostsquad** [vivaxy/gacp#122]
I've found it hard to follow along with what's happening in the `gif` in the Readme, and when I show this tool to someone else, they say the same thing.

**Comment by vivaxy** [comment]
Updated with ![ezgif com-gif-maker](https://user-images.githubusercontent.com/4216856/166616171-e9737ab1-ac13-426a-9ee5-ff4b6b7f493a.gif)
