### ISSUE TITLE
Please do not push tags by default (`--follow-tags`)

### ISSUE THREAD

**Issue by ghostsquad** [vivaxy/gacp#123]
`--follow-tags` should not be true by default, and configurable. I was just bitten by using `gacp` and having a local tag pushed that i didn't want upstream.

**Comment by ghostsquad** [comment]
problematic line is here:
https://github.com/vivaxy/gacp/blob/master/src/gacp.ts#L89

**Comment by vivaxy** [comment]
Thanks you for the suggestion.
Remove `--follow-tags` from default options may break the current behavior. It should be introduced with a major version.
