### ISSUE TITLE
no-verify 行为异常

### ISSUE THREAD

**Issue by RunningCoderLee** [vivaxy/gacp#124]
3.0.0 版本支持了 no-verify，我在使用的时候发现好像默认是开启 `no-verify` 的，当我在 配置中添加了 `verify: true` 后或者是在命令行里添加 `--no-verify=true`，git 提交时才会触发 `husky` 配置的 hook 校验

代码里的逻辑是不是写反了，我理解 `--no-verify=true` 时代表的应该是不校验？

**Comment by vivaxy** [comment]
@RunningCoderLee 多谢指正
