### ISSUE TITLE
Avoid using git add .

### ISSUE THREAD

**Issue by divanvb** [vivaxy/gacp#37]
Hi

Any change to get a config option to avoid committing all files? I'd like to split the commits but currently, all files get added & committed?

**Comment by vivaxy** [comment]
How do you like to add files with the `gacp` module?

I suppose there are some proposals:

# 1
- Run `git add` by yourself.
- Run `gacp --no-add`

# 2
- Run `gacp`, prompts for files to add.
- Confirm the files to add.

**Comment by divanvb** [comment]
@vivaxy Thanks for the swift reply. 

1.  I see the "--no-add" is not documented or am I just looking in the wrong place?
2. When running only "gacp", it doesn't prompt me to add files. It just starts the commit process.

I'd add a certain amount of files to stage and then run the gacp command to create the relevant commit message etc. git-cz & gitmoji alone allow for this.

**Comment by vivaxy** [comment]
@divanvb Both options are not supported yet. I was asking about opinions.

**Comment by divanvb** [comment]
@vivaxy Oh my apologies, I didn't understand the question correctly then. I think adding files yourself would be best as I know people have gotten used to adding files via the command line or using something like VS Code to just quickly add it. So I'd go for option 1.

**Comment by vivaxy** [comment]
@divanvb Sorry, I didn't make myself understood. Maybe change the word `options` to `proposals` is better.
I prefer option 1 too. I will try to provide this option soon, and meanwhile, PR is welcomed.

**Comment by divanvb** [comment]
Cool. Will see if I get some time to add this. Work & university is a bit hectic at the moment.

**Comment by divanvb** [comment]
Thank for the quick add man, you're a legend 💪
