### ISSUE TITLE
`terse` not `tense`

### ISSUE THREAD

**Issue by ghostsquad** [vivaxy/gacp#39]
I noticed that `gacp` is asking me to write a `short, imperative tense description`. I think the word to be used is `terse`.

**Comment by vivaxy** [comment]
Thanks for pointing out.

**Comment by vivaxy** [comment]
@ghostsquad `imperative tense` means `imperative mood` here. See:
1. https://github.com/conventional-changelog/commitlint/blob/master/docs/reference-rules.md#body-tense-deprecated
2. https://github.com/commitizen/cz-conventional-changelog/blob/e7bd5462966d00acb03aca394836b5427513681c/engine.js#L96

**Comment by ghostsquad** [comment]
you are right! my mistake. Maybe you could just remove the word altogether? I think saying `imperative description` still works well.

**Comment by vivaxy** [comment]
> you are right! my mistake. Maybe you could just remove the word altogether? I think saying `imperative description` still works well.

To be discussed.

**Comment by vivaxy** [comment]
It's a common word when talking about the commit messages in commitlint, I think it would be better if we keep it that way.

**Comment by ghostsquad** [comment]
Yes, I think a revert is needed here. I apologize for the churn.
