### ISSUE TITLE
Multi-line longer description

### ISSUE THREAD

**Issue by ghostsquad** [vivaxy/gacp#40]
How do I do a longer multi-line description when asked for a "Provide a longer description of the change" ?

**Comment by ghostsquad** [comment]
make the behavior configurable, both as a default in the config file, but also an overriding flag.

## Implementation

If you pass `--edit` you'll be dropped into your user defined editor to create the longer commit body (pre-filled with everything else that's set prior)

Look at the `git config` for `core.editor` and use that defined program to write the commit message (which has been pre-filled with everything set prior). You can then fall back to looking for environment variables `VISUAL` or `EDITOR` with a hardcoded fallback to `vi`. Similar to how you can do this with `git`.

To maintain backwards compatibility, without flags, support single line messages (kind of like `git -m`).

Users can create bash aliases, or change the configuration to support a default behavior if they wish.

Note, that if the default behavior can be set to `--edit` behavior in the config, then it would would be also useful to have a `--no-edit` CLI option, to override the config file.

**Comment by ghostsquad** [comment]
I've been using this as a daily driver for awhile now, and I absolutely love it. However the problem of not being able to easily write long multi-line commit bodies is still a problem.

My workaround right now is pretty terrible

```
gacp
git commit --amend
git push --force
```

@vivaxy any chance you could spend some time on this? I'd contribute but I'm pretty terrible with javascript and worse with typescript.

**Comment by vivaxy** [comment]
gacp uses prompts underhood. prompts does not supports editor mode for now, see: https://github.com/terkelg/prompts/issues/52.

I think there are two ways of implementing this feature:
1. By typing `\n` means line break in body section. This brings less work to do, and could be done soon.
2. By passing `--edit`, and invoke [node-external-editor](https://github.com/mrkmg/node-external-editor) or `vi`. This brings a lot work to do, and I won't be able to implement it for now.

Let me know which way you prefer. @ghostsquad 

Thanks for your suggestion.

**Comment by ghostsquad** [comment]
I should have posted this a lot earlier. using `\n` doesn't work. it prints a literal `\n` in the commit body.

I would prefer option 2

**Comment by vivaxy** [comment]
Supported in gacp@2.10.0

**Comment by ghostsquad** [comment]
you are kidding! I didn't know you were working on 2.0! I'll download and try it out.
