### ISSUE TITLE
feat: arbitrary post push hooks

### ISSUE THREAD

**Issue by ghostsquad** [vivaxy/gacp#46]
since git doesn't allow for arbitrary post-push hooks, it would be cool if gacp supported it.

would indirectly solve #45 and #44

**Comment by vivaxy** [comment]
Great idea.
We can have some gacp hooks.

**Comment by ghostsquad** [comment]
@vivaxy this still needs documentation

**Comment by vivaxy** [comment]
@ghostsquad See here: https://github.com/vivaxy/gacp/commit/f0d5adf74a1ce9d4a74c3883e006b03c2a02dc66#diff-04c6e90faac2675aa89e2176d2eec7d8R49

If you'd like to config globally, you can create a `.gacprc` file in your home folder(`~/.gacprc`). If you'd like to use this hook in a certain project, you can add a `.gacprc` file in your project root.

The config can be like:
```json
{
  "hooks": {
    "postpush": "${your command}"
  }
}
```
