### ISSUE TITLE
error `Not a git repository` when in a subdirectory of a git repository

### ISSUE THREAD

**Issue by ghostsquad** [vivaxy/gacp#48]
I noticed that I get an error `Not a git repository` when running `gacp` within a subdirectory of a git repository.

Current workaround is to navigate to the root of the git repo, but this is not ideal from a workflow standpoint.

**Comment by vivaxy** [comment]
Good point.

**Comment by vivaxy** [comment]
Thank you for your suggestion. Please try `gacp@2.9.0`.
