### ISSUE TITLE
fatal 'origin\nupstream' does not appear to be a git repository

### ISSUE THREAD

**Issue by ghostsquad** [vivaxy/gacp#92]
whenever I used GACP on a fork of a repository, and I have multiple remotes (origin & upstream), gacp fails to push with an error like:

```
 2 files changed, 20 insertions(+)
fatal: 'origin
upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

as you can see, there's definitely something off with this message, and it appears it's getting a list of remotes, and using both (with a newline between them) in the command.

gacp should probably not assume which remote to push to. Simply using the tracking of the branch should be enough.

**Comment by ghostsquad** [comment]
I think I found the root of this issue, via https://github.com/vivaxy/git/issues/47

**Comment by vivaxy** [comment]
@ghostsquad Thank you for your feedback and looking into the root cause.
Please try gacp@3.0.3.

**Comment by wmcnamee-coreweave** [comment]
sorry, I never replied to this. I'm running the latest, and I still have this problem.

**Comment by ghostsquad** [comment]
ok, I'll pull the latest and touch base later today.

**Comment by wmcnamee-coreweave** [comment]
confirmed, it's a least a better error message now `fatal: no upstream configured for branch 'foo'`
